service: beercraft

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  #default stage is dev if not specified
  name: aws
  runtime: java8
  region: us-east-2
  profile: home
  stage: dev

  environment:
#   FERMENTABLES_TABLE: ${self:service}-${opt:stage, self:provider.stage}-fermentables
    FERMENTABLES_TABLE: Fermentables
    HOPS_TABLE: Hops

  iamRoleStatements:
  - Effect: Allow
    Action:
    - dynamodb:Query
    - dynamodb:Scan
    - dynamodb:GetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.FERMENTABLES_TABLE}"
  - Effect: Allow
    Action:
    - dynamodb:Query
    - dynamodb:Scan
    - dynamodb:GetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.HOPS_TABLE}"

package:
  artifact: server/target/server-${opt:stage, self:provider.stage}.jar

functions:
  index:
    handler: beercraft.Handler

    events:
      - http:
          path: debug
          method: get
      - http:
          path: fermentables
          method: post
      - http:
          path: fermentables
          method: get
      - http:
          path: fermentables/{id}
          method: delete
      - http:
          path: hops
          method: post
      - http:
          path: hops
          method: get
      - http:
          path: hops/{id}
          method: delete

resources:
  Resources:
    FermentablesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
        -
          AttributeName: Id
          AttributeType: S
        KeySchema:
        -
          AttributeName: Id
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.FERMENTABLES_TABLE}
    HopsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
        -
          AttributeName: Id
          AttributeType: S
        KeySchema:
        -
          AttributeName: Id
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.HOPS_TABLE}

